### ISSUE TITLE
Unable click last row buttons

### ISSUE THREAD

**Issue by ReMo-20** [appium/appium-inspector#771] opened 2023-04-12 16:52 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Not fit to screen _ So cannot able to acess below buttons

## Environment

- I am running Appium Desktop version _<Appium-Inspector-linux-2023.2.1>_.
- I am on (pick one):
    - [ +] Linux

**Comment by eglitise** [comment] 2023-05-03 06:17
I assume this is the same issue that was fixed in 2023.3.1, but the Linux release build was broken.
@ReMo-20 please check with version 2023.4.2 or newer. If it's still reproducible, please add a screenshot.

**Comment by eglitise** [comment] 2023-05-17 06:05
Closing due to no response

**Closed by eglitise** 2023-05-17 06:05 UTC
