### ISSUE TITLE
bug: the inspector is always loading after starting

### ISSUE THREAD

**Issue by mystufo** [appium/appium-inspector#1799] opened 2024-11-17 11:42 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my  Capability Sets are：
{
  "platformName": "ios",
  "appium:automationName": "XCuiTest",
  "appium:udid": "00008101-xxxxxxx"
}
After i press the start session button, the inspector is always loading with no picture.
It worked well just last week
The appium scripts can be run success on this iphone.
I have tried another macbook and iphone, it showed also the same result.

![image](https://github.com/user-attachments/assets/be6c0a68-3573-4006-85d6-1e34e0174ffb)

### Expected Behavior

I want the inspector works normally

### Operating System

Mac

### Appium Inspector Version

 2023.12.2

### Appium Version

2.5.2

### Further Information

[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"ios","appium:automationName":"XCuiTest","appium:udid":"00008101-00112DE238E1401E","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"ios","appium:automationName":"XCuiTest","appium:udid":"00008101-00112DE238E1401E","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@97c8] Calling AppiumDriver.createSession() with args: [{"platformName":"ios","appium:automationName":"XCuiTest","appium:udid":"00008101-00112DE238E1401E","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"ios","appium:automationName":"XCuiTest","appium:udid":"00008101-00112DE238E1401E","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@97c8] Event 'newSessionRequested' logged at 1731843303917 (19:35:03 GMT+0800 (中国标准时间))
[Appium] Attempting to find matching driver for automationName 'XCuiTest' and platformName 'ios'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/lijianfei/.appium/node_modules/appium-xcuitest-driver
[Appium] Requiring driver at /Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/build/index.js
[AppiumDriver@97c8] Appium v2.5.2 creating new XCUITestDriver (v5.12.2) session
[AppiumDriver@97c8] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@97c8] Appium's BaseDriver version is 9.6.0
[AppiumDriver@97c8] XCUITestDriver's BaseDriver version is 9.6.0
[XCUITestDriver@b7b7] Creating session with W3C capabilities: {
[XCUITestDriver@b7b7]   "alwaysMatch": {
[XCUITestDriver@b7b7]     "platformName": "ios",
[XCUITestDriver@b7b7]     "appium:automationName": "XCuiTest",
[XCUITestDriver@b7b7]     "appium:udid": "00008101-00112DE238E1401E",
[XCUITestDriver@b7b7]     "appium:includeSafariInWebviews": true,
[XCUITestDriver@b7b7]     "appium:newCommandTimeout": 3600,
[XCUITestDriver@b7b7]     "appium:connectHardwareKeyboard": true
[XCUITestDriver@b7b7]   },
[XCUITestDriver@b7b7]   "firstMatch": [
[XCUITestDriver@b7b7]     {}
[XCUITestDriver@b7b7]   ]
[XCUITestDriver@b7b7] }
[XCUITestDriver@b7b7] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[XCUITestDriver@b7b7] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.
[XCUITestDriver@b7b7 (108d7853)] Session created with session id: 108d7853-1c8f-44e3-a5af-978c1237394d
[XCUITest] Current user: 'lijianfei'
[XCUITestDriver@b7b7 (108d7853)] Available devices: 00008101-00112DE238E1401E
[XCUITest] Creating iDevice object with udid '00008101-00112DE238E1401E'
[XCUITestDriver@b7b7 (108d7853)] Determining device to run tests on: udid: '00008101-00112DE238E1401E', real device: true
[XCUITestDriver@b7b7 (108d7853)] No platformVersion specified. Using device version: '17.6.1'
[XCUITestDriver@b7b7 (108d7853)] Normalized platformVersion capability value '17.6.1' to '17.6'
[XCUITestDriver@b7b7 (108d7853)] Event 'xcodeDetailsRetrieved' logged at 1731843304003 (19:35:04 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Event 'appConfigured' logged at 1731843304003 (19:35:04 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Event 'resetStarted' logged at 1731843304003 (19:35:04 GMT+0800 (中国标准时间))
[XCUITest] Reset: running ios real device reset flow
[XCUITestDriver@b7b7 (108d7853)] Event 'resetComplete' logged at 1731843304004 (19:35:04 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Using WDA path: '/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@b7b7 (108d7853)] Using WDA agent: '/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Executing /Library/Frameworks/Python.framework/Versions/3.10/bin/pyidevice crash list --udid 00008101-00112DE238E1401E --network --format json
[XCUITestDriver@b7b7 (108d7853)] Event 'logCaptureStarted' logged at 1731843304701 (19:35:04 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Setting up real device
[XCUITestDriver@b7b7 (108d7853)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 00008101-00112DE238E1401E on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for 00008101-00112DE238E1401E:8100
[XCUITestDriver@b7b7 (108d7853)] Parsed BUILD_DIR configuration value: '/Users/lijianfei/Library/Developer/Xcode/DerivedData/WebDriverAgent-dnypekloopjxlpepasgjpmtjuvwa/Build/Products'
[XCUITestDriver@b7b7 (108d7853)] Got derived data root: '/Users/lijianfei/Library/Developer/Xcode/DerivedData/WebDriverAgent-dnypekloopjxlpepasgjpmtjuvwa'
[XCUITestDriver@b7b7 (108d7853)] Starting WebDriverAgent initialization with the synchronization key '/Users/lijianfei/Library/Developer/Xcode/DerivedData/WebDriverAgent-dnypekloopjxlpepasgjpmtjuvwa'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1704165750866","time":"Nov 17 2024 15:46:23","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.4","version":"17.6.1"},"device":"iphone","ios":{"ip":"10.60.69.199"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
[XCUITestDriver@b7b7 (108d7853)] Upgrade timestamp of the currently bundled WDA: 1704165750866
[XCUITestDriver@b7b7 (108d7853)] Upgrade timestamp of the WDA on the device: 1704165750866
[XCUITestDriver@b7b7 (108d7853)] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITestDriver@b7b7 (108d7853)] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITestDriver@b7b7 (108d7853)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[XCUITestDriver@b7b7 (108d7853)] Event 'wdaStartAttempted' logged at 1731843305119 (19:35:05 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1704165750866","time":"Nov 17 2024 15:46:23","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"17.4","version":"17.6.1"},"device":"iphone","ios":{"ip":"10.60.69.199"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
[XCUITestDriver@b7b7 (108d7853)] Event 'wdaSessionAttempted' logged at 1731843305125 (19:35:05 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Sending createSession command to WDA
[XCUITestDriver@b7b7 (108d7853)] Matched '/session' to command name 'createSession'
[XCUITestDriver@b7b7 (108d7853)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}
[XCUITestDriver@b7b7 (108d7853)] Got response with status 200: {"value":{"sessionId":"CF3E2479-8FBB-495D-87EF-B7A2F3F9F8F4","capabilities":{"sdkVersion":"17.6.1","device":"iphone"}},"sessionId":"CF3E2479-8FBB-495D-87EF-B7A2F3F9F8F4"}
[XCUITestDriver@b7b7 (108d7853)] Determined the downstream protocol as 'W3C'
[XCUITestDriver@b7b7 (108d7853)] Event 'wdaSessionStarted' logged at 1731843305131 (19:35:05 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Event 'wdaStarted' logged at 1731843305131 (19:35:05 GMT+0800 (中国标准时间))
[BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[AppiumDriver@97c8] New XCUITestDriver session created successfully, session 108d7853-1c8f-44e3-a5af-978c1237394d added to master session list
[AppiumDriver@97c8] Event 'newSessionStarted' logged at 1731843305131 (19:35:05 GMT+0800 (中国标准时间))
[XCUITestDriver@b7b7 (108d7853)] Cached the protocol value 'W3C' for the new session 108d7853-1c8f-44e3-a5af-978c1237394d
[XCUITestDriver@b7b7 (108d7853)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","automationName":"XCuiTest","udid":"00008101-00112DE238E1401E","includeSafariInWebviews":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true}}
[HTTP] <-- POST /session 200 1216 ms - 446
[HTTP] 
[HTTP] --> GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/screenshot
[HTTP] {}
[XCUITestDriver@b7b7 (108d7853)] Calling AppiumDriver.getScreenshot() with args: ["108d7853-1c8f-44e3-a5af-978c1237394d"]
[XCUITestDriver@b7b7 (108d7853)] Executing command 'getScreenshot'
[XCUITestDriver@b7b7 (108d7853)] Taking screenshot with WDA
[XCUITestDriver@b7b7 (108d7853)] Matched '/screenshot' to command name 'getScreenshot'
[XCUITestDriver@b7b7 (108d7853)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/CF3E2479-8FBB-495D-87EF-B7A2F3F9F8F4/screenshot] with no body
[XCUITestDriver@b7b7 (108d7853)] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAABJIAAAnkCAIAAADZI9xUAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAABJKgAwAEAAAAAQAACeQAAAAAOMw3jQAAAAlwSFlzAAALEwAACxMBAJqcGAAAABxpRE9UAAAAAgAAAAAAAATyAAAAKAAABPIAAATyAAH6BiTdOTcAAEAASURBVHgB7N0HvB5Vgf9/1pdldXV/a9ledN39b3fVVXGxo4ioiKCACkhHOqEEEopIJxBKCi2hSRWkV0GRIhCSkF5uy70pt+X23lJg/98nJzk5OTPP3Ofe+5TzPM/H17yuZ+Y5c2bmPfOQ+71n5sxuQyNbmBBAAAEEEEAAAQQQQAABBIIV2C3YPWPHEEAAAQQQQAABBBBAAAEEJEBso7MRAQQQQAABBBBAAAEEEAhagNgW9OnhTwsIIIAAAggggAACCCCAALGN2IYAAggggAACCCCAAAIIBC1AbAv69PB3BQQQQAABBBBAAAEEEECA2EZsQwABBBBAAAEEEEAAAQSCFiC2BX16+LsCAggggAACCCCAAAIIIEBsI7YhgAACCCCAAAIIIIAAAkELENuCPj38XQEBBBBAAAEEEEAAAQQQILYR2xBAAAEEEEAAAQQQQACBoAWIbUGfHv6ugAACCCCAAAIIIIAAAggQ24htCCCAAAIIIIAAAggggEDQAsS2oE8Pf1dAAAEEEEAAAQQQQAABBIhtxDYEEEAAAQQQQAABBBBAIGgBYlvQp4e/KyCAAAIIIIAAAggggAACxDZiGwIIIIAAAggggAACCCAQtACxLejTw98VEEAAAQQQQAABBBBAAAFiG7ENAQQQQAABBBBAAAEEEAhagNg...
[XCUITestDriver@b7b7 (108d7853)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABJIAAAnkCAIAAADZI9xUAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAABJKgAwAEAAAAAQAACeQAAAAAOMw3jQAAAAlwSFlzAAALEwAACxMBAJqcGAAAABxpRE9UAAAAAgAAAAAAAATyAAAAKAAABPIAAATyAAH6BiTdOTcAAEAASURBVHgB7N0HvB5Vgf9/1pdldXV/a9ledN39b3fVVXGxo4ioiKCACkhHOqEEEopIJxBKCi2hSRWkV0GRIhCSkF5uy70pt+X23lJg/98nJzk5OTPP3Ofe+5TzPM/H17yuZ+Y5c2bmPfOQ+71n5sxuQyNbmBBAAAEEEEAAAQQQQAABBIIV2C3YPWPHEEAAAQQQQAABBBBAAAEEJEBso7MRAQQQQAABBBBAAAEEEAhagNgW9OnhTwsIIIAAAggggAACCCCAALGN2IYAAggggAACCCCAAAIIBC1AbAv69PB3BQQQQAABBBBAAAEEEECA2EZsQwABBBBAAAEEEEAAAQSCFiC2BX16+LsCAggggAACCCCAAAIIIEBsI7YhgAACCCCAAAIIIIAAAkELENuCPj38XQEBBBBAAAEEEEAAAQQQILYR2xBAAAEEEEAAAQQQQACBoAWIbUGfHv6ugAACCCCAAAIIIIAAAggQ24htCCCAAAIIIIAAAggggEDQAsS2oE8Pf1dAAAEEEEAAAQQQQAABBIhtxDYEEEAAAQQQQAABBBBAIGgBYlvQp4e/KyCAAAIIIIAAAggggAACxDZiGwIIIIAAAggggAACCCAQtACxLejTw98VEEAAAQQQQAABBBBAAAFiG7ENAQQQQAABBBBAAAEEEAhagNgW9Onh7woI...
[HTTP] <-- GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/screenshot 200 221 ms - 310244
[HTTP] 
[HTTP] --> GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/window/rect
[HTTP] {}
[XCUITestDriver@b7b7 (108d7853)] Calling AppiumDriver.getWindowRect() with args: ["108d7853-1c8f-44e3-a5af-978c1237394d"]
[XCUITestDriver@b7b7 (108d7853)] Executing command 'getWindowRect'
[XCUITestDriver@b7b7 (108d7853)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/CF3E2479-8FBB-495D-87EF-B7A2F3F9F8F4/window/size] with no body
[XCUITestDriver@b7b7 (108d7853)] Got response with status 200: {"value":{"width":390,"height":844},"sessionId":"CF3E2479-8FBB-495D-87EF-B7A2F3F9F8F4"}
[XCUITestDriver@b7b7 (108d7853)] Responding to client with driver.getWindowRect() result: {"width":390,"height":844,"x":0,"y":0}
[HTTP] <-- GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/window/rect 200 82 ms - 48
[HTTP] 
[HTTP] --> GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/source
[HTTP] {}
[XCUITestDriver@b7b7 (108d7853)] Calling AppiumDriver.getPageSource() with args: ["108d7853-1c8f-44e3-a5af-978c1237394d"]
[XCUITestDriver@b7b7 (108d7853)] Executing command 'getPageSource'
[XCUITestDriver@b7b7 (108d7853)] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[XCUITestDriver@b7b7 (108d7853)] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/CF3E2479-8FBB-495D-87EF-B7A2F3F9F8F4/source?format=xml&scope=AppiumAUT] with no body
[XCUITestDriver@b7b7 (108d7853)] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x302abb000","traceback":"(\n\t0   CoreFoundation                      0x0000000196fd0f2c 76A3B198-3C09-323E-8359-0D4978E156F5 + 540460\n\t1   libobjc.A.dylib                     0x000000018ee732b8 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001970da480 76A3B198-3C09-323E-8359-0D4978E156F5 + 1627264\n\t3   CoreFoundation                      0x0000000196f6dfb4 76A3B198-3C09-323E-8359-0D4978E156F5 + 135092\n\t4   CoreFoundation                      0x0000000196f6d8d0 _CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   0x0000000100bc2f50 -[XCUIElement(FBUtilities) fb_waitUntilStableWithTimeout:] + 308\n\t6   WebDriverAgentLib                   0x0000000100b78ac8 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 632\n\t7   WebDriverAgentLib                   0x0000000100b78...
[W3C] Matched W3C error code 'unknown error' to UnknownError
[XCUITestDriver@b7b7 (108d7853)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x302abb000
[XCUITestDriver@b7b7 (108d7853)]     at errorFromW3CJsonCode (/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1064:25)
[XCUITestDriver@b7b7 (108d7853)]     at ProxyRequestError.getActualError (/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:933:14)
[XCUITestDriver@b7b7 (108d7853)]     at JWProxy.command (/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
[XCUITestDriver@b7b7 (108d7853)]     at processTicksAndRejections (node:internal/process/task_queues:105:5)
[XCUITestDriver@b7b7 (108d7853)]     at XCUITestDriver.proxyCommand (/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:109:35)
[XCUITestDriver@b7b7 (108d7853)]     at XCUITestDriver.mobileGetSource (/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)
[XCUITestDriver@b7b7 (108d7853)]     at XCUITestDriver.getPageSource (/Users/lijianfei/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:9)
[HTTP] <-- GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/source 500 16 ms - 1430
[HTTP] 
[HTTP] --> GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/timeouts
[HTTP] {}
[XCUITestDriver@b7b7 (108d7853)] Calling AppiumDriver.getTimeouts() with args: ["108d7853-1c8f-44e3-a5af-978c1237394d"]
[XCUITestDriver@b7b7 (108d7853)] Executing command 'getTimeouts'
[XCUITestDriver@b7b7 (108d7853)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/timeouts 200 3 ms - 42
[HTTP] 
[iProxy@00008101:8100] The connection has been closed
[HTTP] --> GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/timeouts
[HTTP] {}
[XCUITestDriver@b7b7 (108d7853)] Calling AppiumDriver.getTimeouts() with args: ["108d7853-1c8f-44e3-a5af-978c1237394d"]
[XCUITestDriver@b7b7 (108d7853)] Executing command 'getTimeouts'
[XCUITestDriver@b7b7 (108d7853)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /session/108d7853-1c8f-44e3-a5af-978c1237394d/timeouts 304 1 ms - -
[HTTP]

**Comment by mystufo** [comment] 2024-11-17 11:47
I have tried differen inspector such as 2024.9.1, 2023.5.1, 2024.9.1, none of them works normally

**Comment by eglitise** [comment] 2024-11-17 22:24
> [XCUITestDriver@b7b7 (108d7853)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x302abb000

Please upgrade XCUITest driver to >=7.24.15 and rebuild WDA.
[Refer to the XCUITest driver documentation for Xcode/iOS version compatibility.](https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/#xcodeios-version-support)
Closing as duplicate of #1700.

**Comment by eglitise** [comment] 2024-11-17 22:26
Are you using Xcode 16?

**Comment by hiteshdarjibacancy** [comment] 2024-11-18 05:47
In windows, Appium inspector not working I am using latest

**Comment by eglitise** [comment] 2024-11-18 10:22
@hiteshdarjibacancy if you are using Xcode 16/iOS 18, please check my previous comment. If this is not the case, please create a separate issue and provide your Appium server logs.

**Closed** 2024-11-26 10:34 UTC
Labels: need info
