### ISSUE TITLE
bug: Child Elements of flatlist unreachable

### ISSUE THREAD

**Issue by Harsh121998** [appium/appium-inspector#1229] opened 2023-12-01 06:35 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have multiple components inside a flatlist in my iOS app. These include custom button's, labels and touchable opacity. I am not able to inspect these individually in Appium Inspector.

### Expected Behavior

Like other elements in my iOS app, i should be able to inspect each component, built-in or custom individually on Appium inspector, with seperate Test-Ids.

### Operating System

Mac

### Appium Inspector Version

2023.10.4

### Appium Version

2.2.1

### Further Information

 <Flatlist
                 accessibilityLabel = {AccessibilityLabelStrings.1} accessibilityHint = {AccessibilityHintStrings.1} testID = 
                 {TestIds.1}
                 renderItem={(data) =>
                  
                              <View style={{ padding: 10, height: 100, width: '100%' }} accessibilityLabel = 
                     {AccessibilityLabelStrings.2}
                accessibilityHint = {AccessibilityHintStrings.2}
                testID = {TestIds.2}>
                              <View style={{ backgroundColor: 'green', flex: 1, flexDirection: 'row' }}accessibilityLabel = {AccessibilityLabelStrings.3}
                accessibilityHint = {AccessibilityHintStrings.3}
                testID = {TestIds.3}>
                              <ActionButton text='Tap Me' onPress={() => console.log('tappedd')} accessibilityLabel = {AccessibilityLabelStrings.4}
                accessibilityHint = {AccessibilityHintStrings.4}
                testID = {TestIds.4}/>
                            <View style={{ backgroundColor: 'yellow', flex: 1 }} accessibilityLabel = {AccessibilityLabelStrings.5}
                accessibilityHint = {AccessibilityHintStrings.5}
                testID = {TestIds.5}>
                                <ActionButton text='Tap Me-44' onPress={() => console.log('tappedd')} accessibilityLabel = {AccessibilityLabelStrings.6}
                accessibilityHint = {AccessibilityHintStrings.6}
                testID = {TestIds.6}/>
                            </View>
                        </View>
                    </View>
                }
               />

**Comment by eglitise** [comment] 2023-12-01 06:55
This is not an Inspector-specific issue. Closing as duplicate of https://github.com/appium/appium/issues/19464

**Closed by eglitise** 2023-12-01 06:55 UTC
Labels: bug
