### ISSUE TITLE
Inspect element in ios mobile app using appium inspector in windows

### ISSUE THREAD

**Issue by subhrasubudhi09** [appium/appium-inspector#469] opened 2022-06-16 06:31 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

iOS elements are not getting detected for our automation.
 We have a react native application. The same is working fine in Android.
The attributes which we used in the UI elements are accessibilityLabel and testID. Even though we are unable to detect the elements for iOS in appium

## Environment

- I am running Appium Inspector 2022.5.4
- Appium version : 1.22.3-4
- I am on (pick one):
     - [x] Windows
    
![173990242-4af6502a-ff52-4582-9ef1-1e71dfad740b](https://user-images.githubusercontent.com/48639356/174006302-0b32581a-8a61-4686-a439-0c8b3a47e138.png)

**Comment by jlipps** [comment] 2022-06-16 21:01
closing as duplicate of https://github.com/appium/appium-desktop/issues/2058

**Closed by jlipps** 2022-06-16 21:01 UTC

**Comment by aragalstyan2000** [comment] 2023-05-30 16:46
Hello @jlipps. I still have the same issue and https://github.com/appium/appium-desktop/issues/2058 is not a valid issue link. Thanks!

**Comment by jlipps** [comment] 2023-05-30 23:03
ah right, that issue tracker got closed. in any case it looks like you are using a very old version of the inspector. please try the latest and open a new issue with details if it's still not working.

**Comment by dapolJS** [comment] 2023-08-17 08:59
I am having exactly same issue, and version does not affect how inspector sees those elements

**Comment by gautamsamyak** [comment] 2023-09-01 12:24
I am also facing same issue in ios react native app.
