### ISSUE TITLE
Enhancement request to show video in appium inspector using MJPEG functionality

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-inspector#296] opened 2022-02-10 21:17 UTC
Enhancement request to show video in appium inspector using MJPEG functionality

Hi,

Since we already have MJPEG server in appium, possible to use it to show live video in canvas of appium inspector?

**Comment by jlipps** [comment] 2022-02-10 23:49
yes, I have a branch with this mostly working somewhere. just need to find some time to work on it.

**Comment by krishtoautomate** [comment] 2022-02-11 00:12
Nice. With canvas its easy to activate highlight elements when focused

**Comment by jlipps** [comment] 2022-05-09 19:38
duplicate of #121

**Closed by jlipps** 2022-05-09 19:38 UTC
