### ISSUE TITLE
bug: Unable to locate some elements after scrolling it into view for the first time.

### ISSUE THREAD

**Issue by shinobi01** [appium/appium-inspector#964] opened 2023-07-06 05:16 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some elements are visible but unable to locate on Appium inspector, but after switching display, those elements are able to be located.

### Expected Behavior

Elements should be able to locate when it is visible for the first time.

### Operating System

Mac

### Appium Inspector Version

2022.2.1

### Appium Version

2.0.0-beta.67

### Further Information

I have an element on iOS device, "see more" button, it was hidden by default and will has a judgement whether it has more contents to show, if yes then it will be set to not hidden and shows on application.

For now, after scrolling the see more button into view, the functions are working correctly, the see more button could be seen and able to open more contents display, but from appium inspector, when we trying to locate the element, we couldn't find the locator, after we switch display on application, we are able to locate it. is there something missed in code level or it is an issue on appium inspector?
Thank you very much.

**Locate for first time:**
<img width="796" alt="locate element first time" src="https://github.com/appium/appium-inspector/assets/19482522/ea3fc924-d620-448e-8c83-e53649704342">

**Locate after switch display:**
<img width="796" alt="locate element after switch display" src="https://github.com/appium/appium-inspector/assets/19482522/88ca809f-d9cf-40c6-9f74-b252f0355453">

**Comment by eglitise** [comment] 2023-07-06 05:52
I don't think this is a problem with the inspector, it merely shows the source retrieved by the XCUITest driver. I would suggest trying to run an actual test that attempts to find this button - if it still fails, the issue is likely within the app itself.
I'm also not entirely sure what do you mean by 'switch display' - maybe you mean navigating to a different screen and back? There could be some app logic there that affects this button. It may also be worth checking if the button appears after a longer timeout.

**Comment by shinobi01** [comment] 2023-07-06 05:57
@eglitise thank you for your answer. 
Yes, I have tried several times, it always failed on the first try to locate element.
'switch display' is same as your understanding, navigating to other screen and back, then the 'see more' button could be locate.
And also I tried to wait for a long time to locate the element, but no help.

**Comment by eglitise** [comment] 2023-07-06 07:38
Thanks for the info - to me this sounds like an issue with the app itself.

**Comment by shinobi01** [comment] 2023-07-06 08:04
Hi @eglitise are you familiar with iOS developing? do you know if there are some actions needed to reload layout after setting 'see more' button not hidden?

**Comment by eglitise** [comment] 2023-07-06 09:10
Sorry, no, I'm not very familiar with iOS development.

**Comment by eglitise** [comment] 2023-07-12 07:24
Closing as not an issue

**Closed by eglitise** 2023-07-12 07:24 UTC
Labels: not a bug
