### ISSUE TITLE
bug: Switching espresso drivers via updateSettings doesn't work at all

### ISSUE THREAD

**Issue by bronik** [appium/appium-inspector#1128] opened 2023-10-13 06:30 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- start **Espresso driver**
- go to **Commands** -> **Session** -> **updateSettings**
- enter {"driver":"compose"} and press **Execute Command**

**Actual result:** got message: 
_'' result
null_

### Expected Behavior

after pressing **Execute Command** (see current behaviour block) - espresso driver switch to compose driver

### Operating System

Mac

### Appium Inspector Version

2023.8.2, 2023.8.4 

### Appium Version

2.1.3

### Further Information

1) appium server doesn't get my command. console log shows only:
[debug] [EspressoDriver@2085 (9b10c7b1)] Calling AppiumDriver.getTimeouts() with args: ["9b10c7b1-3118-4a81-9442-0a389482ff69"]
[debug] [EspressoDriver@2085 (9b10c7b1)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
nothing else is logging

2) espresso driver version 2.25.9

3) capabilities: 
https://gist.github.com/bronik/43757d7c77f4e8c721fb149fc9af3425

**Comment by bronik** [comment] 2023-10-13 06:36
tested on App Version: 2023.5.1
works as expected

and i've got message:
_'updateSettings' result
null_

**Comment by eglitise** [comment] 2023-10-13 07:51
Thanks for the report. I believe this is a duplicate of #1068, which has been fixed in #1069. The fix will be included in the next release.

**Closed by eglitise** 2023-10-13 07:51 UTC
Labels: bug
