### ISSUE TITLE
bug: The click point does not match the accurate position of the element in latest version(2023.10.4)

### ISSUE THREAD

**Issue by yifansue** [appium/appium-inspector#1154] opened 2023-10-26 08:42 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the latest version [Appium-Inspector-mac-2023.10.4.dmg](https://github.com/appium/appium-inspector/releases/download/v2023.10.4/Appium-Inspector-mac-2023.10.4.dmg), the click point does not match the accurate position of the icon.
<img width="1098" alt="Screen Shot 2023-10-26 at 16 26 08" src="https://github.com/appium/appium-inspector/assets/108262131/4bdc57a2-2062-4ad5-8d69-723fef312c8e">

### Expected Behavior
The click point should match the accurate position of the icon.
There is no such problem when using the older version.(for example [Appium-Inspector-mac-2023.6.1.dmg](https://github.com/appium/appium-inspector/releases/download/v2023.6.1/Appium-Inspector-mac-2023.6.1.dmg)) 
<img width="1277" alt="Screen Shot 2023-10-26 at 16 36 31" src="https://github.com/appium/appium-inspector/assets/108262131/03e7e84a-c139-405a-a2a8-9193d1930be1">

### Operating System

Mac

### Appium Inspector Version

Appium-Inspector-mac-2023.10.4.dmg

### Appium Version

2.2.0

**Comment by eglitise** [comment] 2023-10-26 13:17
Thanks for the report. From what I can tell, it seems this happens when the app is launched while the device is in landscape orientation.
For now you can work around this by having the device in portrait orientation before launching the Inspector session. Once the session has been created, you can turn your device to landscape orientation and refresh the screenshot.

**Comment by yifansue** [comment] 2023-10-27 03:19
Thank you for the reply. The device I'm using can only be in landscape orientation, so I will continue using the older version for now. I look forward to it being fixed in the future.👍

**Comment by eglitise** [comment] 2023-11-13 19:50
@yifansue the latest version 2023.11.1 includes a fix for this issue.

**Comment by yifansue** [comment] 2023-11-14 02:59
@eglitise thanks a lot, but the issue persists from my end.🥹

<img width="1098" alt="Screen Shot 2023-11-14 at 10 54 09" src="https://github.com/appium/appium-inspector/assets/108262131/64302b4b-c1b5-4580-aab9-5802746937c3">

**Comment by eglitise** [comment] 2023-11-14 17:40
Interesting. Could you please provide the following screen size data about your device?

1. The dimensions detected by UiAutomator2: in the Inspector, switch to Commands tab, open Execute Script -> executeScript, and in the `executeScriptCommand` field, enter `mobile:viewportRect` and run it. It should return a set of 4 coordinate points.
2. The dimensions detected by `adb`: in the terminal, run `adb shell wm size`

**Comment by yifansue** [comment] 2023-11-15 03:33
@eglitise Sure~
1. mobile:viewportRect
{
  "left": 0,
  "top": 24,
  "width": 1280,
  "height": 728
}
2. adb shell wm size > Physical size: 800x1280

**Comment by eglitise** [comment] 2023-11-15 13:10
Thanks. These details seem fine, so I'm still unsure of the cause. Could you please also provide the full Appium log from before starting an Inspector session, to after the screenshot has loaded?
You can redact any sensitive information if necessary.

**Comment by yifansue** [comment] 2023-11-16 03:40
okok, here is the Appium log of start Appium -> start Inspector
[appium_log.txt](https://github.com/appium/appium-inspector/files/13371938/appium_log.txt)

**Comment by eglitise** [comment] 2023-11-16 13:34
Thanks for the log. Unfortunately I don't see anything odd here either. Can you perhaps try again with the `images` plugin disabled?
Also, do you know which was the last Inspector version that was working for you? Maybe 2023.7.1?

**Comment by yifansue** [comment] 2023-11-17 04:51
hi~
1. Have tried with the images plugin disabled, but the problem still persists.
2. Yes, very correct! The latest version that was working for me is 2023.7.1.

**Comment by eglitise** [comment] 2023-11-30 12:15
@yifansue I've identified one issue that could be related to your problem. Just to confirm, after you've created an Inspector session, if you then press the refresh button, do the highlighter positions change?

**Comment by yifansue** [comment] 2023-12-05 08:09
hi @eglitise the highlighter positions do not change after pressing the refresh button.

**Closed** 2023-12-19 11:21 UTC
Labels: bug

**Comment by eglitise** [comment] 2023-12-20 20:28
@yifansue I believe I finally managed to reproduce your issue and fixed the problem. This fix is included in the latest version (2023.12.2). Please let me know if it helps 🙏

**Comment by yifansue** [comment] 2023-12-25 09:02
@eglitise it works!!! 🥳🥳🥳 cooooooooool~~~~~ Thank you so much! ❤️
