### ISSUE TITLE
Appium Inspector - getting timeout 304 

### ISSUE THREAD

**Issue by yogeshMahajan2218** [appium/appium-inspector#1773] opened 2024-10-24 07:48 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Session does not get started, timeout 304 keeps getting 

```
Executing command 'getTimeouts'
[1ee2bb6e][XCUITestDriver@9bef] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[1ee2bb6e][HTTP] <-- GET /session/1ee2bb6e-d742-4349-9825-9130396dba3b/timeouts 304 5 ms - - 
```

<img width="1348" alt="Screenshot 2024-10-24 at 11 58 17 AM" src="https://github.com/user-attachments/assets/82d3547e-bfe5-49ea-9a61-e7a82df5649c">

### Expected Behavior

Session should get started in appium inspector.

### Operating System

Mac

### Appium Inspector Version

2024.9.1

### Appium Version

2.12.0

**Comment by yogeshMahajan2218** [comment] 2024-10-24 10:03
Attaching the logs. please check.

also adding screenshot where we can see, in appium inspector it keeps loadings and loading..session does not get started.

Note: this is only happening with iOS simulators for Android it works fine

**Comment by yogeshMahajan2218** [comment] 2024-10-24 10:04
[appium server logs.txt](https://github.com/user-attachments/files/17505145/appium.server.logs.txt)
![Uploading Screenshot 2024-10-24 at 3.32.07 PM.png…]()

**Comment by yogeshMahajan2218** [comment] 2024-10-24 10:04
![Uploading Screenshot 2024-10-24 at 3.32.07 PM.png…]()

**Comment by yogeshMahajan2218** [comment] 2024-10-24 10:04
[appium server logs.txt](https://github.com/user-attachments/files/17505151/appium.server.logs.txt)

**Comment by yogeshMahajan2218** [comment] 2024-10-24 10:05
<img width="1108" alt="Screenshot 2024-10-24 at 3 32 07 PM" src="https://github.com/user-attachments/assets/e687ef16-20f5-4def-92d8-9435f455a768">

**Comment by eglitise** [comment] 2024-10-24 11:53
> xcuitest@5.16.1

> Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x6000030ed100

Please upgrade XCUITest driver to >=7.24.15 and rebuild WDA.
[Refer to the XCUITest driver documentation for Xcode/iOS version compatibility.](https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/#xcodeios-version-support)
Closing as duplicate of #1700.

**Closed by eglitise** 2024-10-24 11:53 UTC
Labels: need info

**Comment by yogeshMahajan2218** [comment] 2024-10-24 12:56
Hey @eglitise 
Can you guide me how we can rebuild WDA ?

**Comment by eglitise** [comment] 2024-10-24 18:53
Follow the same instructions as you did when you initially configured your iPhone for automation. [Check the documentation for details.](https://appium.github.io/appium-xcuitest-driver/latest/preparation/)

**Comment by eglitise** [comment] 2024-10-24 18:54
Personally I use the full manual configuration approach, so the way I would rebuild WDA is by just opening the Xcode project, selecting the WDA scheme and my target device, and then selecting Product -> Test. Xcode would then build the project and install the WDA app on the device.

**Comment by vhsantos26** [comment] 2024-11-06 17:05
> > xcuitest@5.16.1
> 
> > Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x6000030ed100
> 
> Please upgrade XCUITest driver to >=7.24.15 and rebuild WDA. [Refer to the XCUITest driver documentation for Xcode/iOS version compatibility.](https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/#xcodeios-version-support) Closing as duplicate of #1700.

Thanks, it helps me a lot 🚀

**Comment by eglitise** [comment] 2024-11-21 13:31
@irfana28 please read the above comments. HTTP 304 is expected behavior and is not an issue. If you are using Xcode 16/iOS 18, [refer to my previous comment. ](https://github.com/appium/appium-inspector/issues/1773#issuecomment-2435067964)
