### ISSUE TITLE
How to resolve issue for appium inspector when entering PlatformName as iOS, getting error that platformName should be MAC,WINDoWS etc. Not able to start session because of this. 

### ISSUE THREAD

**Issue by chetan160689** [appium/appium-inspector#440] opened 2022-05-26 22:50 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by chetan160689** [comment] 2022-05-26 22:52
Using mac m1 and latest appium desktop and appium inspector

**Comment by chetan160689** [comment] 2022-05-27 06:26
Actual Error Message after clicking on Start Session :

Error 
Failed to create session. Error : Platform can be one of MAC, WIN8, XP, and ANY

<img width="436" alt="Screenshot 2022-05-27 at 08 22 47" src="https://user-images.githubusercontent.com/106354774/170643189-f1d4fda2-d6d1-4679-8b85-042763ceea49.png">

**Comment by chetan160689** [comment] 2022-05-30 22:03
Any update on this?

**Comment by chetan160689** [comment] 2022-05-30 22:06
mokhnach@gmail.com
@mykola-mokhnach - Do you have any solution on this? I can see all others can use PlatformName as iOS but for me i am getting above error which are not mobile platforms.

**Comment by chetan160689** [comment] 2022-05-30 22:08
@jlipps - Can you also look from your end?

**Comment by kkauffman-incomm** [comment] 2022-08-18 18:52
I'm seeing the same issue on both macOS Big Sur and Windows 10. I have to install Appium Desktop 1.19.1, back when Appium Inspector was bundled with that, in order to get a working version (@chetan160689, here is a work-around, if you need it).

I am attempting to connect to a device via BrowserStack. Here is my capability set:
`{
  "appium:deviceName": "iPhone SE 2020",
  "platformName": "iOS",
  "appium:app_url": "bs://[REDACTED]",
  "appium:platformVersion": "13"
}`

The above capability set was created with the [instructions provided by BrowserStack](https://www.browserstack.com/docs/app-automate/appium/integrations/appium-desktop). The checkbox to "Automatically add necessary Appium vendor prefixes on start" does not prepend `appium:` to the front of `platformName`, and I'm not sure why. Is `platformName` now defunct in place of something else?

**Comment by KazuCocoa** [comment] 2022-08-20 18:08
It seems like browserstack specific behavior as https://github.com/appium/appium-inspector/issues/437 .

platformName is W3C standard, so it should not have a vendor prefix like `appium:` as https://www.w3.org/TR/webdriver/

Duplicate of https://github.com/appium/appium-inspector/issues/437

**Closed by KazuCocoa** 2022-08-20 18:08 UTC

**Comment by kkauffman-incomm** [comment] 2022-09-01 15:41
For those in the future: this was indeed a BrowserStack issue, but only in the documentation. The [webpage with instructions for how to connect to BrowserStack](https://www.browserstack.com/docs/app-automate/appium/integrations/appium-desktop) is using BrowserStack's custom `app_url` capability instead of the W3C `app` capability. It's a small detail that is easy to overlook.

This morning, I received this response from BrowserStack support:
> I request you to please follow the W3C protocol for the capability generator: [https://www.browserstack.com/app-automate/capabilities?tag=w3c](https://www.browserstack.com/app-automate/capabilities?tag=w3c)

>We will be checking internally to update this [page](https://www.browserstack.com/docs/app-automate/appium/integrations/appium-desktop) regarding W3C protocol capabilities and will be publishing those changes accordingly.
