### ISSUE TITLE
Inconsistent highlighted locators with the source elements

### ISSUE THREAD

**Issue by fjrKurniawan** [appium/appium-inspector#272] opened 2022-01-12 07:03 UTC
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Case 1:
- Hover the cursor in the snapshot
- The highlighted locators don't get the active application

![image](https://user-images.githubusercontent.com/32128622/149079933-4a87928d-f253-4c37-9cb6-320a41ff5672.png)

Case 2:
- Enter a locator in Appium Desktop and search for it.
- It shows a list of elements that match the locator.
- When we tap on any element, it should get highlighted in the Snapshot which is not happening now.

<img width="1265" alt="Screen Shot 2022-01-12 at 13 57 07" src="https://user-images.githubusercontent.com/32128622/149079660-0f9e5064-6f50-48ad-bba0-1785ed7f9d24.png">

## Environment

- I am running Appium Desktop version 2021.12.2 with Espresso.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment] 2022-01-12 17:51
duplicate of #217

**Closed by jlipps** 2022-01-12 17:51 UTC
