### ISSUE TITLE
bug: Microsoft Defender SmartScreen prevented the installation

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [appium/appium-inspector#1786] opened 2024-11-07 05:08 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was just tried to install appium inspector. When i am trying to open .exe file the below alert is shown.

<img width="884" alt="Screenshot 2024-11-07 103438" src="https://github.com/user-attachments/assets/577554b6-dee7-4bc7-bfbc-525a3eb60a2a">

### Expected Behavior

N/A

### Operating System

Windows

### Appium Inspector Version

2024.9.1

**Comment by eglitise** [comment] 2024-11-07 07:47
Duplicate of #1134

**Closed by eglitise** 2024-11-07 07:47 UTC
Labels: bug
