### ISSUE TITLE
inspector doesnt reconize platformName ='iOS' as  valid 

### ISSUE THREAD

**Issue by HamzaMiz** [appium/appium-inspector#666] opened 2022-11-22 15:48 UTC
## Appium Desktop + inspector

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _1.22.3.4
- I am on (pick one):
    - [ ok ] Mac
    - [ ] Windows
    - [ ] Linux
<img width="1273" alt="Screenshot 2022-11-22 at 16 48 17" src="https://user-images.githubusercontent.com/94066399/203358949-ea774674-ff3a-4972-81ca-c9c538ddf311.png">

**Comment by KazuCocoa** [comment] 2022-11-22 17:52
Could you share the appium server log?

**Comment by Aze77777** [comment] 2023-01-04 03:04
I had the same problem.
I have tried the 1.22.3 and 1.21.0 versions of appium, and I will encounter such problems（Macbook Pro and iphone8，iphone12）
![936695382276160](https://user-images.githubusercontent.com/120435541/210476671-bfbd8f25-ea6a-447b-b5fc-3302d951500e.png)
![607978382276150](https://user-images.githubusercontent.com/120435541/210476682-f4a35a63-8249-413a-a078-5be18250906d.png)

**Comment by Aze77777** [comment] 2023-01-04 03:54
Run WebDriverAgent.xcodeproj, which comes with the appium, and an error is reported. Later, download the latest package of webdriverAgent on github to replace the original webdriverAgent. I wonder if it will have any impact

**Comment by Aze77777** [comment] 2023-01-04 07:29
> ## Appium 桌面 + 检查器
> * [ ] 我已经确认我的问题没有出现在 Appium 上，应该作为 Appium 桌面问题进行调查
> 
> ## 问题所在
> _将此部分替换为问题描述_
> 
> ## 环境
> * 我正在运行 Appium 桌面版本 _1.22.3.4
> * 我在（选择一个）：
>   * [ 好的 ]苹果电脑
>   * [ ] 窗户
>   * [ ] Linux目录
> 
> <img alt="截图 2022-11-22 在 16 48 17" width="1273" src="https://user-images.githubusercontent.com/94066399/203358949-ea774674-ff3a-4972-81ca-c9c538ddf311.png">

Hello, I solved this problem. When you configure the environment, it is estimated that the entire WDA package will be replaced and overwritten with a new one. You can only overwrite a few files instead of all. After that, appium can be used normally
![Uploading 195464853-3e7e67c4-f841-4513-ae03-ca2ebbd0e706.png…]()

**Comment by Aze77777** [comment] 2023-01-04 07:30
> ## Appium 桌面 + 检查器
> * [ ] 我已经确认我的问题没有出现在 Appium 上，应该作为 Appium 桌面问题进行调查
> 
> ## 问题所在
> _将此部分替换为问题描述_
> 
> ## 环境
> * 我正在运行 Appium 桌面版本 _1.22.3.4
> * 我在（选择一个）：
>   * [ 好的 ]苹果电脑
>   * [ ] 窗户
>   * [ ] Linux目录
> 
> <img alt="截图 2022-11-22 在 16 48 17" width="1273" src="https://user-images.githubusercontent.com/94066399/203358949-ea774674-ff3a-4972-81ca-c9c538ddf311.png">

![Uploading 195464853-3e7e67c4-f841-4513-ae03-ca2ebbd0e706.png…]()

**Comment by Aze77777** [comment] 2023-01-04 07:31
<img width="282" alt="195464853-3e7e67c4-f841-4513-ae03-ca2ebbd0e706" src="https://user-images.githubusercontent.com/120435541/210505161-048aed5e-4928-4b81-96b2-14e5d4e2601e.png">

**Comment by Aze77777** [comment] 2023-01-04 07:32
![Uploading 195464853-3e7e67c4-f841-4513-ae03-ca2ebbd0e706.png…]()

**Comment by HamzaMiz** [comment] 2023-01-05 09:47
thanks bro , i fixed it long time ago, i m using appium 2.0 now but it will be a solution for other people

**Comment by eglitise** [comment] 2023-05-25 19:01
If I understand this correctly, the problem was caused by `appium-webdriveragent` included in the old Appium Desktop, which was not working for some reason, and an attempt was made to replace it with a newer `appium-webdriveragent` version. But I assume the differences in the newer versions were also causing issues (as they are only compatible with Appium 2).

For future readers, please use Appium Inspector + standalone Appium instead of Appium Desktop, and also consider moving to Appium 2.

**Closed by eglitise** 2023-05-25 19:01 UTC
Labels: NeedsInfo
