### ISSUE TITLE
Please report this issue at: https://github.com/appium/appium-inspector/issues/new/choose Full error trace: TypeError: t is not a function

### ISSUE THREAD

**Issue by Shanmugam-77** [appium/appium-inspector#1375] opened 2024-02-29 11:04 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Inspect_Issue](https://github.com/appium/appium-inspector/assets/159113937/173c94d6-64a3-4527-bc81-0c296b423ca7)

### Expected Behavior

The existing desired capabilities not opened when the user click the name.

### Operating System

Windows

### Appium Inspector Version

2024.2.1

**Comment by eglitise** [comment] 2024-02-29 14:10
Possible duplicate of #1344. Please try with version 2024.2.2.

**Comment by eglitise** [comment] 2024-03-06 06:58
Closing due to no response

**Closed by eglitise** 2024-03-06 06:58 UTC
Labels: need info
