### ISSUE TITLE
Is it possible to save screenshots of individual elements?

### ISSUE THREAD

**Issue by gauravgandhi1315** [appium/appium-inspector#1188] opened 2023-11-10 17:10 UTC
### Current Behavior

I can't save it right now

### Suggested Solution

It would be great if we can save screenshots of individual elements

**Comment by eglitise** [comment] 2023-11-10 21:36
Closing as duplicate of #1096.
But I've looked into this for a bit, it was not as straightforward as the full page screenshot.

**Closed by eglitise** 2023-11-10 21:36 UTC
Labels: enhancement
