### ISSUE TITLE
appium-inspector is throwing an error when search icon is clicked

### ISSUE THREAD

**Issue by tanTarantino** [appium/appium-inspector#886] opened 2023-06-08 20:53 UTC
## Appium or Appium Inspector?

You are reporting an issue at the Appium Inspector repository. Appium Inspector is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Inspector but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Inspector version _2023.5.2_.
- I am on (pick one):
    - [ x ] Mac
    - [ ] Windows
    - [ ] Linux
[error.docx](https://github.com/appium/appium-inspector/files/11692895/error.docx)

**Comment by eglitise** [comment] 2023-06-08 20:57
Please attach your error directly in text. Eitherway, I'm fairly certain this is a duplicate of #869. Check if you have provided the `appium:automationName` capability in your session.

**Comment by eglitise** [comment] 2023-06-11 08:58
Issue has been fixed in version 2023.6.1.

**Closed by eglitise** 2023-06-11 08:58 UTC
