### ISSUE TITLE
platformName capability needs to be passed error even though it is being passed connecting to BitBar through Appium inspector

### ISSUE THREAD

**Issue by vishalweb** [appium/appium-inspector#123] opened 2021-09-02 05:07 UTC
I am unable to launch apk (android) or ipa (iOS) connecting to Bitbar cloud through Appium desktop Appium inspector tool.
It complains that platformName capability needs to be passed, even though I have passed the same.
On checking Appium server logs on bitbar , it somehow gets converted to platform rather than platformName.

Please note, no such issue happens when I run through maven passing the capabilities , apps launch fine.
It seems Appium Desktop ,inspector when passing the desired capabilities has some issues. I can see similar issues raised for this , but I have tried solutions like typing all capabilities from scratch instead of pasting json but they did not work

https://stackoverflow.com/questions/55389453/appium-desktop-keep-on-asking-for-platformname-capability-even-if-it-is-added

## Environment

- I am running Appium Desktop version : 1.20.2, also tried on 1.18 and 1.21
- I am on :
    - [ ] Mac Big Sur

Below is the error

2021-09-02 04:59:45:638 - [debug] [MJSONWP] Encountered internal error running command: Error: You must include a platformName capability

capabilities passed in Appium inspector:  (Note: hidden app, bitbar_app values for security purpose, also provided correct api_key when connecting to bitbar cloud through Appium inspector)

{
  "platformName": "iOS",
  "deviceName": "iPhone device",
  "automationName": "XCUITest",
  "bitbar_device": "Apple iPhone 11 A2221 13.0",
  "bitbar_app": "*******",
  "bitbar_target": "ios",
  "app": "***********************"
}

**Comment by jlipps** [comment] 2021-09-02 16:52
Please try with the latest version of the Appium Inspector, which is no longer part of Appium Desktop.

**Comment by vishalweb** [comment] 2021-09-03 00:09
Hi @jlipps ,
I downloaded the latest version of Appium inspector (Appium-Inspector-mac-2021.8.5.dmg) and tried to connect (Note: app, bitbar_app deliberately hidden due to security in below image but providing correctly)
But its giving the error shown in image below. 

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/8010956/131930856-46e5d352-dab2-41a4-9009-14eda759245e.png">

I also tried selecting the option Automatically add necessary Appium vendor prefixes on start (both removing the bitbar_ from bitbar capabilities and keeping them but get the below error of testdroid capabilities in that case )

![image](https://user-images.githubusercontent.com/8010956/131931266-3d275c40-c4c0-4e18-8674-969348a1744a.png)

**Comment by KazuCocoa** [comment] 2021-09-03 02:38
I guess https://github.com/appium/appium-inspector/blob/c9eb36c52f82c9a980a7d1c2bede60f928706115/app/renderer/actions/Session.js#L312-L313 should have appium prefix...?
So, this inspector sends W3C capabilities, but they initially added non-vendor prefix capabilities for them.
We should ask vendors to check their vendor prefixes.

**Comment by ashish0401** [comment] 2021-09-03 02:51
Hey Kazu,
I there any specific reason why we need to pass testdroid capabilities explicitly here ???
Because once we connect the external cloud using api key, I think this should not be mandatory.
I even tried with and without appium prefix. nothing changes.
But my question is why its mandatory at first place ?

**Comment by KazuCocoa** [comment] 2021-09-03 04:04
We don't know basically. Vendors added their own sections.
We mostly only reviewed some mandatory items like icon data.

**Comment by jlipps** [comment] 2021-09-03 04:16
Yeah, the issue is that wdio requires a vendor prefix even before the new session request is sent. Assuming testdroid accepts caps with prefixes, then it should be an easy fix (just adding the appium prefix to all vendor caps in actions/Session.js).

**Comment by ashish0401** [comment] 2021-09-03 04:22
ok so we should talk to our vendor and ask there prefix then ?
and then try with that to connect and see if it works.

**Comment by KazuCocoa** [comment] 2021-09-03 07:45
Yes, since we don't know what they should be.

I'll try to find github account in past PRs later to ping them.
But if you could send their support contact etc, it will be great.

**Comment by ashish0401** [comment] 2021-09-06 12:14
Hey there,
I spoke to them and they informed me that they dont use any prefix.
The message I got from that is : 
`I saw this Github ticket and I don't really know what prefix they mean, we don't use any prefix, all our capabilities are described in our documentation:
https://support.smartbear.com/bitbar/docs/testing-with-bitbar/automated-testing/appium/desired-capabilities.html
and we use those provided by Appium:
https://appium.io/docs/en/writing-running-appium/caps/

We run our Client Side Appium check test runs every day and haven't noticed any issues :`

For the bitbar support this will be a good start : https://support.smartbear.com/bitbar/

**Comment by KazuCocoa** [comment] 2021-09-06 18:31
Then, I guess they don't support W3C capabilities...?
The original contribution was https://github.com/appium/appium-desktop/pull/594.

As Appium team, it is difficult to maintain all vendor features as voluntary contributions since we don't have their accounts and cannot guarantee their feature by us. Vendor features were provided by vendors (so some vendors were already tested). Let me ping the original contributors in another issue if they can check this repository feature.

**Comment by KazuCocoa** [comment] 2021-09-06 18:45
I'll ping them in https://github.com/appium/appium-inspector/issues/128

**Comment by PatrickFlaherty** [comment] 2021-09-13 14:20
Hi,
I'm seeing the same issue .
An unknown server-side error occurred while processing the command. Original error: **You must include a platformName capability**
I'm using Bitbar who is saying this is an Appium Desktop issue? Can you confirm? Is there an earlier version of Inspector that might work?

**Comment by KazuCocoa** [comment] 2021-09-13 17:08
Could you share the full appium server log?

So far, https://github.com/appium/appium-inspector/pull/118 is a known issue to access to some vendors. You could try the branch to see if the error still occurs. Vendors that have checked in https://github.com/appium/appium-inspector/issues/128#issuecomment-913809011 works with the branch for now. So potentially the issue is BitBar specific.

I've already mentioned a person who ordinally added Bitbar capability to AD. Afaik, no one contributes to this project from BitBar, so we basically have no way to guarantee their availability. We need their help to make sure their feature. (So I mentioned a person who originally added the feature)

**Comment by PatrickFlaherty** [comment] 2021-09-13 17:24
Sure:
2021-09-13 15:01:24:497 - [Appium] Welcome to Appium v1.21.0
2021-09-13 15:01:24:499 - [Appium] Non-default server args:
2021-09-13 15:01:24:499 - [Appium]   logTimestamp: true
2021-09-13 15:01:24:499 - [Appium]   logNoColors: true
2021-09-13 15:01:24:500 - [Appium]   defaultCapabilities: {
2021-09-13 15:01:24:500 - [Appium]     chromedriverExecutableDir: /chromedrivers/bin
2021-09-13 15:01:24:500 - [Appium]     chromedriverChromeMappingFile: /chromedrivers/chromedriverMapping.json
2021-09-13 15:01:24:500 - [Appium]   }
2021-09-13 15:01:24:500 - [Appium]   relaxedSecurityEnabled: true
2021-09-13 15:01:24:501 - [Appium]   denyInsecure: {
2021-09-13 15:01:24:501 - [Appium]     0: chromedriver_autodownload
2021-09-13 15:01:24:502 - [Appium]   }
2021-09-13 15:01:24:502 - [Appium]   udid: 98131FFBA003BK
2021-09-13 15:01:24:503 - [Appium] Deprecated server args:
2021-09-13 15:01:24:503 - [Appium]   -U => --default-capabilities
2021-09-13 15:01:24:503 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2021-09-13 15:01:24:503 - [Appium]   chromedriverExecutableDir: /chromedrivers/bin
2021-09-13 15:01:24:504 - [Appium]   chromedriverChromeMappingFile: /chromedrivers/chromedriverMapping.json
2021-09-13 15:01:24:526 - [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2021-09-13 15:01:25:372 - [HTTP] --> GET /wd/hub/status
2021-09-13 15:01:25:372 - [HTTP] {}
2021-09-13 15:01:25:374 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2021-09-13 15:01:25:374 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.21.0"}}
2021-09-13 15:01:25:378 - [HTTP] <-- GET /wd/hub/status 200 5 ms - 68
2021-09-13 15:01:25:378 - [HTTP]
2021-09-13 15:01:25:943 - [HTTP] --> POST /wd/hub/session
2021-09-13 15:01:25:943 - [HTTP] {"desiredCapabilities":{"appActivity":"com.ravemobilesafety.raveguardian.activities.SplashScreenActivity","appPackage":"com.ravemobilesafety.raveguardian","autoAcceptAlerts":false,"automationName":"UiAutomator2","bitbar_platformName":"Android","deviceName":"Android Phone","newCommandTimeout":180,"noReset":true,"testdroid_source":"appiumdesktop","connectHardwareKeyboard":true,"platform":"Android","app":"/var/lib/jenkins/jobs/Public.GooglePixel4XL-US_98131FFBA003BK.0fdb23fbd45f4a15/workspace/application.apk"}}
2021-09-13 15:01:25:944 - [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.ravemobilesafety.raveguardian.activities.SplashScreenActivity","appPackage":"com.ravemobilesafety.raveguardian","autoAcceptAlerts":false,"automationName":"UiAutomator2","bitbar_platformName":"Android","deviceName":"Android Phone","newCommandTimeout":180,"noReset":true,"testdroid_source":"appiumdesktop","connectHardwareKeyboard":true,"platform":"Android","app":"/var/lib/jenkins/jobs/Public.GooglePixel4XL-US_98131FFBA003BK.0fdb23fbd45f4a15/workspace/application.apk"},null,null]
2021-09-13 15:01:25:944 - [debug] [BaseDriver] Event 'newSessionRequested' logged at 1631545285944 (15:01:25 GMT+0000 (Coordinated Universal Time))
2021-09-13 15:01:25:946 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1631545285946 (15:01:25 GMT+0000 (Coordinated Universal Time))
2021-09-13 15:01:26:021 - [debug] [MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps (/opt/testdroid/appium-1.21.0/node_modules/appium/lib/appium.js:232:13)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at AppiumDriver.createSession (/opt/testdroid/appium-1.21.0/node_modules/appium/lib/appium.js:340:66)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at commandExecutor (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at AppiumDriver.executeCommand (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:15)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at AppiumDriver.executeCommand (/opt/testdroid/appium-1.21.0/node_modules/appium/lib/appium.js:549:26)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at asyncHandler (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:34)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at /opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at Layer.handle [as handle_request] (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at next (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at Route.dispatch (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at Layer.handle [as handle_request] (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at /opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2021-09-13 15:01:26:021 - [debug] [MJSONWP]     at Function.process_params (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2021-09-13 15:01:26:022 - [debug] [MJSONWP]     at next (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2021-09-13 15:01:26:022 - [debug] [MJSONWP]     at logger (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/morgan/index.js:144:5)
2021-09-13 15:01:26:022 - [debug] [MJSONWP]     at Layer.handle [as handle_request] (/opt/testdroid/appium-1.21.0/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2021-09-13 15:01:26:023 - [HTTP] <-- POST /wd/hub/session 500 79 ms - 179
2021-09-13 15:01:26:023 - [HTTP]

**Comment by KazuCocoa** [comment] 2021-09-13 17:34
> 2021-09-13 15:01:25:943 - [HTTP] {"desiredCapabilities":{"appActivity":"com.ravemobilesafety.raveguardian.activities.SplashScreenActivity","appPackage":"com.ravemobilesafety.raveguardian","autoAcceptAlerts":false,"automationName":"UiAutomator2","bitbar_platformName":"Android","deviceName":"Android Phone","newCommandTimeout":180,"noReset":true,"testdroid_source":"appiumdesktop","connectHardwareKeyboard":true,"platform":"Android","app":"/var/lib/jenkins/jobs/Public.GooglePixel4XL-US_98131FFBA003BK.0fdb23fbd45f4a15/workspace/application.apk"}}

Did you use this appium-inspector?
If so, it seems their server drops W3C capabilities. We don't know of their internal handler, so their help is necessary in https://github.com/appium/appium-inspector/issues/128 to fix it.
As https://github.com/appium/appium-inspector/issues/128, appium-inspector will W3C spec as its primary way to work with Appium 2.0.

**Comment by PatrickFlaherty** [comment] 2021-09-13 17:41
Yes, I used appium inspector 1.21.0 for the log I posted. I also added bitbar_platformName just in case they needed a their prefix.
Does W3C use platformName or Platform? It seems that the inspector converted my platformName to platform in the call to the server.
thanks

**Comment by KazuCocoa** [comment] 2021-09-13 18:07
> Does W3C use platformName or Platform?

No. `platformName` is `platformName`. I guess it is done by the BitBar internal.

**Comment by KazuCocoa** [comment] 2021-09-13 18:09
so, sorry. appium uses `platformName`. But `platform` should not work.

**Comment by jlipps** [comment] 2021-09-13 21:42
> Yes, I used appium inspector 1.21.0 for the log I posted

That is not the inspector as developed here. 

> I also added bitbar_platformName just in case they needed a their prefix.

It should be just `platformName`

**Comment by KazuCocoa** [comment] 2021-09-29 06:24
Moves to => https://github.com/appium/appium-inspector/issues/128

**Closed by KazuCocoa** 2021-09-29 06:24 UTC
