### ISSUE TITLE
getting the error while launching the inspector "Unexpected Error: Cannot read property 'client' of null"

### ISSUE THREAD

**Issue by ramugadde** [appium/appium-inspector#1033] opened 2023-08-12 11:22 UTC
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unexpected Error: Cannot read property 'client' of null"

### Expected Behavior

Appium inspector should start with installed application in emulator.

### Operating System

Mac

### Appium Inspector Version

App Version: 2023.8.1 Electron: 13.6.9 Node.js: 14.16.0

### Further Information

Unexpected Error: Cannot read property 'client' of null

**Comment by eglitise** [comment] 2023-08-12 13:56
Possibly duplicate of #1023? But please provide more details on how to reproduce this issue, and your Appium server log as well.

**Comment by ramugadde** [comment] 2023-08-13 05:27
Hi,
yes, its Similar to #1023. While launching the inspector, i am getting the **"Cannot read property 'client' of null"** and app is closing abruptly. 
here is the log for reference:
Unexpected Error: Cannot read property 'client' of null
Please report this issue at: https://github.com/appium/appium-inspector/issues/new/choose
Full error trace:
TypeError: Cannot read property 'client' of null
    at g (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:138:591)
    at y (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:138:1421)
    at renderWithHooks (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at mountIndeterminateComponent (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20074:13)
    at beginWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21587:16)
    at beginWork$1 (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27426:14)
    at performUnitOfWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26560:12)
    at workLoopSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
    at renderRootSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
    at recoverFromConcurrentError (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26096:20)
    at flushSyncCallbacks (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
    at /Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25651:13

**Comment by ramugadde** [comment] 2023-08-13 07:42
Trying to inspect the Wrapper app.

**Comment by eglitise** [comment] 2023-08-13 13:20
I'm not sure I understand what you mean by 'launching the inspector'. As in, does the error appear right after opening the app itself, or when you try to create a new session? To me it seems like this error comes from the code responsible for element search - maybe it appears upon clicking the search element button?
And please share the Appium server log - from the Appium server running in the background, not from the Inspector.

**Comment by eglitise** [comment] 2023-08-17 18:52
Please try with the new 2023.8.2 version.

**Comment by eglitise** [comment] 2023-08-21 06:57
Closing due to no response

**Closed by eglitise** 2023-08-21 06:57 UTC
Labels: bug
