### ISSUE TITLE
Setup Webdriver using Appium 1.2.22

### ISSUE THREAD

**Issue by ps1logi** [appium/appium-inspector#349] opened 2022-03-25 14:02 UTC
## Appium or Appium Desktop?
Appium Desktop 
## The problem

_Need help to setup web driver for 1.2.22_

- I am running Appium Desktop version _<i1.2.22>_.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

Can anyone help me set up webdriver using 1.2.22

**Comment by KazuCocoa** [comment] 2022-03-27 18:01
duplicate of https://github.com/appium/appium-inspector/issues/350

**Closed by KazuCocoa** 2022-03-27 18:01 UTC
